-- ======================================================================
-- Módulo Cobranzas FR - Parámetros de Escalas de Descuento y PPP
-- Base de datos: central (LAKER_SA)
-- ======================================================================

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RO_T_CASHFLOW_COBRANZAS_PARAM_DESC]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[RO_T_CASHFLOW_COBRANZAS_PARAM_DESC] (
        [ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [COD_CLIENT] VARCHAR(20) NOT NULL,
        [MEDIO_PAGO] VARCHAR(30) NOT NULL CONSTRAINT DF_RO_T_CASHFLOW_COB_MEDIO DEFAULT ('ECHEQ'),
        [DIAS_DESDE] INT NOT NULL,
        [DIAS_HASTA] INT NOT NULL,
        [PORCENTAJE_DESC] DECIMAL(5,2) NOT NULL, -- Ej: 8.00 para 8%
        [ACTIVO] BIT NOT NULL CONSTRAINT DF_RO_T_CASHFLOW_COB_ACTIVO DEFAULT (1),
        [FECHA_UPDATE] DATETIME NOT NULL CONSTRAINT DF_RO_T_CASHFLOW_COB_FECHA DEFAULT (GETDATE()),
        [USUARIO] VARCHAR(50) NULL
    );

    CREATE INDEX IX_RO_T_CASHFLOW_COBRANZAS_PARAM_DESC_CLI 
    ON [dbo].[RO_T_CASHFLOW_COBRANZAS_PARAM_DESC] ([COD_CLIENT], [MEDIO_PAGO], [ACTIVO]);
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RO_T_CASHFLOW_COBRANZAS_CLIENTE_CONFIG]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[RO_T_CASHFLOW_COBRANZAS_CLIENTE_CONFIG] (
        [COD_CLIENT] VARCHAR(20) NOT NULL PRIMARY KEY,
        [PPP_MANUAL] INT NULL, -- Si tiene valor, pisa el PPP calculado
        [FECHA_UPDATE] DATETIME NOT NULL CONSTRAINT DF_RO_T_CASHFLOW_COB_CLI_FECHA DEFAULT (GETDATE()),
        [USUARIO] VARCHAR(50) NULL
    );
END
